#
# /home/$USER/.config/mango/conf.d/monitor.conf
#

# [Monitor Rules]
# Parameters:
#         name    = Match by monitor name (supports regex)
#         make    = Match by monitor manufacturer
#         model   = Match by monitor model
#         serial  = Match by monitor serial number
#         width	  = Monitor width
#         height  = Monitor height
#         refresh = Monitor refresh rate
#         x       = X position
#         y       = Y position
#         scale   = Monitor scale
#         vrr     = Enable variable refresh rate
#         rr      = Monitor transform

# Laptop display: 1080p, 60Hz, no rotation
monitorrule = name:eDP-1, width:1920, height:1080, refresh:60, x:0, y:0, scale:1, vrr:0, rr:0

# External monitor: 1080p, 60Hz, positioned to the right
monitorrule = name:HDMI-A-1, width:1920, height:1080, refresh:60, x:1920, y:0, scale:1, vrr:0, rr:0
